### ISSUE TITLE
Feature Ideas / Improvements

### ISSUE THREAD

**Issue by bendulum** [jordancalder/keyword-analyzer#2]
I ran into a couple of issues:
- punctuation symbols are treated as part of words, e.g. "word." or "(word"
- no way to handle case sensitivity, e.g. "word" and "Word" are counted separately
- it seems " symbols are counted as words as well

How realistic is it that you will add support for those cases?

**Comment by jordancalder** [comment]
I'll try and get to that tonight. Or if you want to add them yourself, feel free to add a pull request.

**Comment by bendulum** [comment]
I'm afraid I don't have time as I have loads of work to do. But it's no rush.
By the way, I'm using your module together with https://www.npmjs.com/package/stopwords
As a work around for now I manually remove all punctuation before running the analysis.
It would be really cool to be able to filter out anything that is not a noun...
Will investigate further, thank you.

EDIT: [This module](https://github.com/michaeldelorenzo/keyword-extractor) might provide some inspiration.

**Comment by jordancalder** [comment]
I've added an update and pushed a new version of the package to npm. If this takes care of what you need, go ahead and close the issue. Thanks!
